name: Test
on:
  workflow_dispatch:
jobs:
  run:
    name: Test
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@main
        with:
          python-version: 3.11

      - name: Run
        run: |
          pip install -r requirements.txt
          python -m seleniumwire extractcert
          sudo cp ca.crt /usr/local/share/ca-certificates
          sudo update-ca-certificates
          python main.py -v -f cookies.json https://www.apkmirror.com
